# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loginsample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  # Pods for loginsample

  target 'loginsampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'loginsampleUITests' do
    # Pods for testing
  end

end
